### Problem 1 - Reshape an Array

In [2]:
import numpy as np
arr = np.arange(1, 13)

In [3]:
# A. 3 rows × 4 columns
arr_3x4 = arr.reshape(3, 4)
print(arr_3x4)
print("Shape:", arr_3x4.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [4]:
# B. Reshape into 4 rows × 3 columns
arr_4x3 = arr.reshape(4, 3)
print(arr_4x3)
print("Shape:", arr_4x3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)


In [5]:
# C. Find the shape of both arrays
print("Shape of 3x4 array:", arr_3x4.shape)
print("Shape of 4x3 array:", arr_4x3.shape)

Shape of 3x4 array: (3, 4)
Shape of 4x3 array: (4, 3)


### Problem 2 - Flatten a 2D Array

In [7]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

- 1. Number of rows
- 2. Number of columns
- 3. Shape of the matrix
- 4. Convert the matrix into a 1D array

In [9]:
# 1. Number of rows
print("Number of rows:", matrix.shape[0])

Number of rows: 3


In [10]:
# 2. Number of columns
print("Number of columns:", matrix.shape[1])

Number of columns: 3


In [11]:
# 3. Shape of the matrix
print("Shape:", matrix.shape)

Shape: (3, 3)


In [12]:
# 4. Convert the matrix into a 1D array
flat_array = matrix.flatten()
print("1D array:", flat_array)

1D array: [10 20 30 40 50 60 70 80 90]


### Problem 3 - Combine Two Arrays

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [15]:
# A. Single array containing both
result_a = np.concatenate((a, b))
print(result_a)

[1 2 3 4 5 6]


In [16]:
# B. a and b as separate rows
result_b = np.vstack((a, b))
print(result_b)

[[1 2 3]
 [4 5 6]]


In [17]:
# C. a and b as separate columns
result_c = np.column_stack((a, b))
print(result_c)

[[1 4]
 [2 5]
 [3 6]]


### Problem 3 - Split an Array

In [19]:
import numpy as np
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
import numpy as np

arr = np.arange(1, 13)

# Split into 3 equal parts
parts = np.split(arr, 3)

# Print each part
print("First part:", parts[0])
print("Second part:", parts[1])
print("Third part:", parts[2])

# Sum of each part
print("First sum:", np.sum(parts[0]))
print("Second sum:", np.sum(parts[1]))
print("Third sum:", np.sum(parts[2]))

First part: [1 2 3 4]
Second part: [5 6 7 8]
Third part: [ 9 10 11 12]
First sum: 10
Second sum: 26
Third sum: 42


In [21]:
# Problem 5 - Real-World Sales Data Analysis
import numpy as np

sales = np.array([
    12000, 15000, 11000, 18000,
    20000, 22000, 19000, 25000,
    27000, 24000, 30000, 32000
])

# 1. Reshape into 4 rows and 3 columns
sales_reshaped = sales.reshape(4, 3)

print("Sales by quarter:")
print(sales_reshaped)

# 2. Calculate total sales for each quarter
quarterly_sales = np.sum(sales_reshaped, axis=1)

print("Quarterly sales:", quarterly_sales)

# 3. Find the quarter with the highest sales
highest_quarter_index = np.argmax(quarterly_sales)

print("Highest quarter index:", highest_quarter_index)
print("Highest sales quarter: Q", highest_quarter_index + 1)

# 4. Find highest monthly sales
highest_monthly_sales = np.max(sales)

print("Highest monthly sales:", highest_monthly_sales)

# 5. Find average monthly sales
average_monthly_sales = np.mean(sales)

print("Average monthly sales:", average_monthly_sales)

Sales by quarter:
[[12000 15000 11000]
 [18000 20000 22000]
 [19000 25000 27000]
 [24000 30000 32000]]
Quarterly sales: [38000 60000 71000 86000]
Highest quarter index: 3
Highest sales quarter: Q 4
Highest monthly sales: 32000
Average monthly sales: 21250.0
