### Q.1 Problem 1 — Create an Array

Create a NumPy array containing the numbers:

10, 20, 30, 40, 50

Then print:

- the array
- its data type
- its shape
- its size

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Data type:", arr.dtype)
print("Shape:", arr.shape)
print("Size:", arr.size)

Array: [10 20 30 40 50]
Data type: int32
Shape: (5,)
Size: 5


### Q.2 Problem 2 — Create Special Arrays

Create the following NumPy arrays:

A. An array of 10 zeros

[0 0 0 0 0 0 0 0 0 0]

B. An array of 5 ones

[1 1 1 1 1]

C. Numbers from 1 to 20

[1 2 3 ... 20]

D. Even numbers from 2 to 20

[2 4 6 ... 20]

In [19]:
import numpy as np

# A. Create an array of 10 zeros
arr = np.zeros(10)
print(arr)


# B. Create an array of 5 ones
arr = np.ones(5)
print(arr)


# C. Create numbers from 1 to 20
arr = np.arange(1, 21)
print(arr)


# D. Create even numbers from 2 to 20
arr = np.arange(2, 21, 2)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Q.3 Problem 3 — Array Arithmetic

Given:

a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

Calculate:

- a + b
- a - b
- a * b
- a / b
- a ** 2

In [4]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Square of a:", a ** 2)
print("Square of b:", b ** 2)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Square of a: [ 100  400  900 1600 2500]
Square of b: [ 1  4  9 16 25]


### Q.4 Problem 4 — Find Maximum, Minimum and Average

Given:

marks = np.array([78, 85, 92, 67, 88, 95, 73])

Find:

- Maximum mark
- Minimum mark
- Average mark
- Sum of all marks
- Index of the student with the highest mark

In [22]:
import numpy as np
marks = np.array([78, 85, 92, 67, 88, 95, 73])
Max = np.max(marks)
print("Maximum mark :", Max)

Min = np.min(marks)
print("Minimum mark :", Min)

Avg = np.mean(marks)
print("Average mark :", Avg)

Sum = np.sum(marks)
print("Sum of all mark :", Sum)

Max_Index = np.argmax(marks)
print("Maximum mark :", Max_Index)

Maximum mark : 95
Minimum mark : 67
Average mark : 82.57142857142857
Sum of all mark : 578
Maximum mark : 5


### Q.5 Problem 5  — Temperature Analysis

You have temperatures recorded over 7 days:

temperature = np.array([32, 35, 31, 29, 36, 34, 30])

Using NumPy, find:

- Average temperature
- Highest temperature
- Lowest temperature
- Difference between highest and lowest temperature
- Number of days where temperature was above 32°C
- Find the temperatures that were above 32°C.

In [ ]:
import numpy as np

temperature = np.array([32, 35, 31, 29, 36, 34, 30])

Max_temp = np.max(temperature)
print("Maximum temprature :", Max_temp)

Min_temp = np.min(temperature)
print("Minimum temprature :", Max_temp)

Avg_temp = np.mean(temperature)
print("Average temprature :", Max_temp)

difference = np.max(temperature) - np.min(temperature)
print("Difference:", difference)

days_above_32 = np.sum(temperature > 32)
print("Days above 32°C:", days_above_32)



