### Problem 1 - Scalar Broadcasting

In [2]:
import numpy as np
prices = np.array([100, 200, 300, 400, 500])

In [3]:
# 1. New prices
new_prices = prices + 50
print("New prices:", new_prices)

New prices: [150 250 350 450 550]


In [4]:
# 2. Average
average = np.mean(new_prices)
print("Average:", average)

Average: 350.0


In [5]:
# 3. Difference
difference = np.max(new_prices) - np.min(new_prices)
print("Difference:", difference)

Difference: 400


### Problem 2 - Apply Discount

In [7]:
import numpy as np
products = np.array([1000, 2000, 3000, 4000, 5000])

In [8]:
# 1. Discount amount
discount = products * 0.10
print("Discount:", discount)


Discount: [100. 200. 300. 400. 500.]


In [9]:
# 2. Final prices
final_price = products - discount
print("Final prices:", final_price)


Final prices: [ 900. 1800. 2700. 3600. 4500.]


In [10]:
# 3. Total original price
total_original = np.sum(products)
print("Total original:", total_original)

Total original: 15000


In [11]:
# 4. Total after discount
total_after_discount = np.sum(final_price)
print("Total after discount:", total_after_discount)

Total after discount: 13500.0


### Problem 3 - Matrix + Vector Broadcasting

In [13]:
import numpy as np

marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 79]
])

bonus = np.array([5, 3, 2])

In [14]:
# 1. Add bonus marks
new_marks = marks + bonus
print("New marks:")
print(new_marks)

New marks:
[[75 83 92]
 [65 78 87]
 [93 95 81]]


In [15]:
# 2. Total marks for each student
total_marks = np.sum(new_marks, axis=1)
print("Total marks:", total_marks)

Total marks: [250 230 269]


In [16]:
# 3. Average marks for each student
average_marks = np.mean(new_marks, axis=1)
print("Average marks:", np.round(average_marks, 2))


Average marks: [83.33 76.67 89.67]


In [17]:
# 4. Highest mark
highest_mark = np.max(new_marks)
print("Highest mark:", highest_mark)

Highest mark: 95


### Problem 4 - Vectorization

In [19]:
import numpy as np
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [20]:
result = numbers * 2 + 5
print(result)

[ 7  9 11 13 15 17 19 21 23 25]


### Problem 5 : Real-World Employee Salary Analysis

In [22]:
import numpy as np

salaries = np.array([
    30000, 35000, 40000,
    45000, 50000, 55000,
    60000, 65000, 70000, 75000
])

In [23]:
# 1. Raise amount
raise_amount = salaries * 0.12
print("Raise amount:", raise_amount)

Raise amount: [3600. 4200. 4800. 5400. 6000. 6600. 7200. 7800. 8400. 9000.]


In [24]:
# 2. New salaries
new_salaries = salaries + raise_amount
print("New salaries:", new_salaries)

New salaries: [33600. 39200. 44800. 50400. 56000. 61600. 67200. 72800. 78400. 84000.]


In [25]:
# 3. Average before raise
average_before = np.mean(salaries)
print("Average before:", average_before)

Average before: 52500.0


In [26]:
# 4. Average after raise
average_after = np.mean(new_salaries)
print("Average after:", average_after)

Average after: 58800.0


In [27]:
# 5. Total additional expense
total_additional = np.sum(raise_amount)
print("Total additional expense:", total_additional)

Total additional expense: 63000.0


In [28]:
# 6. Salaries above ₹60,000
above_60000 = new_salaries[new_salaries > 60000]
print("Salaries above ₹60,000:", above_60000)

Salaries above ₹60,000: [61600. 67200. 72800. 78400. 84000.]


In [29]:
# 7. Count employees above ₹60,000
count_above_60000 = np.sum(new_salaries > 60000)
print("Number of employees:", count_above_60000)

Number of employees: 5


In [30]:
# 8. Percentage increase
total_old = np.sum(salaries)
total_new = np.sum(new_salaries)

percentage_increase = ((total_new - total_old) / total_old) * 100
print("Percentage increase:", percentage_increase)

Percentage increase: 12.0
