### Problem 1 - Basic Indexing

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [3]:
# First Element
print("First Element:", arr[0])

First Element: 10


In [4]:
# Last Element
print("Last Element:", arr[-1])

Last Element: 70


In [5]:
# Third Element
print("Third Element:", arr[2])

Third Element: 30


In [6]:
# Second Last Element
print("Second last Element:", arr[-2])

Second last Element: 60


In [7]:
# Element at index 4
print("Element at index 4:", arr[4])

Element at index 4: 50


### Problem 2 - Slicing

In [9]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
# A. First 5 elements
print(arr[:5])

[10 20 30 40 50]


In [11]:
# B. Last 4 elements
print(arr[-4:])

[60 70 80 90]


In [12]:
# C. Elements from index 2 to index 6
print(arr[2:7])

[30 40 50 60 70]


In [13]:
# D. Every second element
print(arr[::2])

[10 30 50 70 90]


In [14]:
# E. Reverse the entire array
print(arr[::-1])

[90 80 70 60 50 40 30 20 10]


### Problem 3 - Boolean Masking

In [16]:
import numpy as np
marks = np.array([45, 67, 82, 39, 91, 56, 74, 88, 32, 95])

In [17]:
# 1. All marks greater than 70
above_70 = marks[marks>70]
print(above_70)

[82 91 74 88 95]


In [18]:
# 2. All marks less than 50
below_50 = marks[marks<50]
print(below_50)

[45 39 32]


In [19]:
# 3. All marks greater than or equal to 80
above_80 = marks[marks>=80]
print(above_80)

[82 91 88 95]


In [20]:
# 4. Number of students who scored above 70
count_above_70 = np.sum(marks>70)
print(count_above_70)

5


In [21]:
# 5. Number of students who failed (marks < 40)
failed_students = np.sum(marks<40)
print(failed_students)

2


### Problem 4 - Replace Values Using Conditions

In [23]:
import numpy as np
temprature = np.array([25, 32, 38, 41, 29, 35, 42, 27])

In [24]:
np.where(temprature>=35,1,0)


array([0, 0, 1, 1, 0, 1, 1, 0])

### Problem 5 - Student Performance Analysis

In [26]:
marks = np.array([45, 78, 92, 56, 34, 88, 67, 95, 41, 73])

In [27]:
# 1. Passing students
passing_students = marks[marks>=50]
print(passing_students)

[78 92 56 88 67 95 73]


In [28]:
# 2. Failing students
failing_marks = marks[marks<50]
print(failing_marks)

[45 34 41]


In [29]:
# 3. Count passing students
count_passing_student = np.sum(marks>=50)
print(count_passing_student)

7


In [30]:
# 4. Count failing students
count_failing_student = np.sum(marks<50)
print(count_failing_student)

3


In [31]:
# 5. Find the highest marks among passing students
highest_passing = np.max(marks[marks >= 50])
print("Highest passing mark:", highest_passing)

Highest passing mark: 95
